spring:
  datasource:
    url: jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: user
      password: password

server:
  port: ${APP_SERVER_PORT}

#jwt:
#  secret: ${JWT_SECRET_KEY}
#  expiration: ${JWT_EXPIRATION_MILLISECOND}