spring:
  datasource:
    url: jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_MODE}
    show-sql: true
    properties:
      hibernate:
            #      naming:
      #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
      jakarta:
        persistence:
          persistence-unit-name: jpa-test
    generate-ddl: true

server:
  port: ${APP_SERVER_PORT}
  address: ${APP_SERVER_ADDRESS}

jwt:
  base64:
    secret: ${JWT_SECRET_KEY}
  prefix: ${JWT_TOKEN_PREFIX}
  header: ${JWT_TOKEN_HEADER}
  expiration: ${JWT_EXPIRATION_MILLISECOND}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
